services:
  fusiondoc:
    image: fusiondoc-local
    container_name: fusiondoc-container
    ports:
      - "3000:3000"
    environment:
      - GITHUB_OWNER=${GITHUB_OWNER}
      - GITHUB_REPO=${GITHUB_REPO}
      - GITHUB_BRANCH=${GITHUB_BRANCH}
      - GITHUB_TOKEN=${GITHUB_TOKEN}
      - GITHUB_DOCS_PATH=${GITHUB_DOCS_PATH}
      - SITE_TITLE=${SITE_TITLE}
      - SITE_LOGO=${SITE_LOGO}
      - FOOTER=${FOOTER}
      - SOCIAL_LINKS=${SOCIAL_LINKS}
      - ENABLE_AUTH_DB=${ENABLE_AUTH_DB}
      - DATABASE_PROVIDER=${DATABASE_PROVIDER}
      - DATABASE_URL=${DATABASE_URL}
      - BETTER_AUTH_SECRET=${BETTER_AUTH_SECRET}
      - BETTER_AUTH_URL=${BETTER_AUTH_URL}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
    build: 
      context: .
      args:
        - GITHUB_OWNER=${GITHUB_OWNER}
        - GITHUB_REPO=${GITHUB_REPO}
        - GITHUB_BRANCH=${GITHUB_BRANCH}
        - GITHUB_TOKEN=${GITHUB_TOKEN}
        - GITHUB_DOCS_PATH=${GITHUB_DOCS_PATH}
        - SITE_TITLE=${SITE_TITLE}
        - SITE_LOGO=${SITE_LOGO}
        - FOOTER=${FOOTER}
        - SOCIAL_LINKS=${SOCIAL_LINKS}
        - ENABLE_AUTH_DB=${ENABLE_AUTH_DB}
        - DATABASE_PROVIDER=${DATABASE_PROVIDER}
        - DATABASE_URL=${DATABASE_URL}
        - BETTER_AUTH_SECRET=${BETTER_AUTH_SECRET}
        - BETTER_AUTH_URL=${BETTER_AUTH_URL}
        - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
        - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
